Correction
CQEN-QDCE/ceai-cqen-web-platform pull request #24
Opened 2022-07-13 15:26 UTC by BasileMvayi

2022-07-13 18:01 UTC, PierreJiji commented on procedure.md
> +# Précision sur la création des pages avec Jekyll:
Il faudrait l'ajouter dans le premier pages à la troisième étape avec ce j'avais proposé au début dans le page README.md

2022-07-18 19:33 UTC, PierreJiji requested changes

2022-07-18 19:33 UTC, PierreJiji commented on README.md
> +-	Un Github Pull Request se faisant accepter sur la branche main OU tout autre push sur la branche main. Il est aussi possible de démarrer le pipeline manuellement à partir de l'interface d'AWS. Pour
```suggestion
-	Un Github Pull Request se faisant accepter sur la branche main OU tout autre push sur la branche main.
```

2022-07-18 19:33 UTC, PierreJiji commented on README.md
> +https://github.com/CQEN-QDCE/ceai-cqen-deployments/tree/main/plateform_web
```suggestion
Voici le [lien](https://github.com/CQEN-QDCE/ceai-cqen-deployments/tree/main/plateform_web) pour que vous puissiez voir les processus de provisionnement  de l'environnement sur AWS et tous les détails de l'architecture.
```

2022-07-20 12:37 UTC, PierreJiji commented on README.md
> +-	Un Github Pull Request se faisant accepter sur la branche main OU tout autre push sur la branche main. Il est aussi possible de démarrer le pipeline manuellement à partir de l'interface d'AWS. Pour
Il serait mieux d'organiser les phrases et les séparer , ils sont comme coller

2022-07-20 14:46 UTC, BasileMvayi commented on README.md
> +-	Un Github Pull Request se faisant accepter sur la branche main OU tout autre push sur la branche main. Il est aussi possible de démarrer le pipeline manuellement à partir de l'interface d'AWS. Pour
ok c'est fait

2022-07-20 14:47 UTC, BasileMvayi commented on README.md
> +Vous pourrez ensuite voir le processus s’exécuter et voir les détails de chaque étape d'exécution en clicant sur le pipeline en exécution.
Fait

2022-07-20 20:04 UTC, PierreJiji requested changes

2022-07-20 20:04 UTC, PierreJiji commented on README.md
> +3. Avoir ruby v3.0.4 ou + installé sur votre poste et faire la commande ```gem install jekyll bundler``` [Suivre la procédure d'installation](./procedure.md)
```suggestion
3. Installez ruby v3.0.4 ou + sur votre poste [Suivre la procédure d'installation](./procedure.md)
4. Exécutez la commande suivante pour installer les gem nécessaires à la plateforme web
```bundler install```
5. Exécutez la commande suivante pour démarrer le serveur 
```bundle exec jekyll server```
```

2022-07-20 20:04 UTC, PierreJiji commented on procedure.md
> + - bundler install
```suggestion
```

2022-07-20 20:21 UTC, PierreJiji requested changes

2022-07-20 20:21 UTC, PierreJiji commented on procedure.md
> +}-->
```suggestion

```bash
decidim@decidim:~$ type rbenv
rbenv is a function
rbenv ()
{
    local command;
    command="${1:-}";
    if [ "$#" -gt 0 ]; then
        shift;
    fi;
    case "$command" in
        rehash | shell)
            eval "$(rbenv "sh-$command" "$@")"
        ;;
        *)
            command rbenv "$command" "$@"
        ;;
    esac
}
```
```

2022-07-20 20:21 UTC, PierreJiji commented on procedure.md
> +  truffleruby+graalvm-20.1.0-->
```suggestion
```
rbenv install -l

Available versions:
  2.5.8
  2.6.6
  3.0.4
  ...
  rbx-5.0
  truffleruby-20.1.0
  truffleruby+graalvm-20.1.0
```
```

2022-07-21 17:52 UTC, PierreJiji approved these changes

2022-07-22 19:41 UTC, gagf01 requested changes
Enlever la mise à jour du système superflue et poussez ça dans main!

2022-07-22 19:41 UTC, gagf01 commented on procedure.md
> +```
Retirer

2022-07-22 19:50 UTC, BasileMvayi commented on procedure.md
> +```
Est-ce que tu pense que préciser cette étape n'est pas importante ?

2022-07-25 17:42 UTC, gagf01 approved these changes

2022-07-25 17:56 UTC, merged