Feature/ajout documentation lab
CQEN-QDCE/ceai-cqen-web-platform pull request #29
Opened 2022-08-11 19:23 UTC by diego-cqen

2022-08-12 14:18 UTC, PierreJiji requested changes

2022-08-12 14:18 UTC, PierreJiji commented on _plugins/index_generator.rb
> +      #self.read_yaml(File.join(site.source, '_layouts'), page.data['layout'])
Avons-nous besoin de ce commentaire ?

2022-08-12 14:18 UTC, PierreJiji commented on Gemfile
> +  gem 'jekyll-optional-front-matter'
Il serait préférable de spécifier une version de ces deux gem 'jekyll-relative-links', 'jekyll-optional-front-matter'

2022-08-12 14:18 UTC, PierreJiji commented on _bash-scripts/legacy/populate-clone.rb
> +        system("rm -rf ../../_experimentations/#{repoName}")
Une question, juste pour comprendre le concept, pourquoi as-tu changé _documentation-labs en _experimentations ?

2022-08-12 17:44 UTC, diego-cqen commented on _plugins/index_generator.rb
> +      #self.read_yaml(File.join(site.source, '_layouts'), page.data['layout'])
C'est vrai. J'ai supprimé.

2022-08-12 17:49 UTC, diego-cqen commented on Gemfile
> +  gem 'jekyll-optional-front-matter'
Corrigé!

2022-08-12 17:51 UTC, diego-cqen commented on _bash-scripts/legacy/populate-clone.rb
> +        system("rm -rf ../../_experimentations/#{repoName}")
Parce que on faisait la confusion entre les résultats des expérimentations et notre documentation du lab (les guides et patrons).
Je voulais laisser plus claire l'endroit au aller chercher nos experimentations e notre documentation.

2022-08-12 18:36 UTC, PierreJiji approved these changes

2022-08-15 14:36 UTC, torjc01 reviewed
Salut Diego, j'ai fait le tour des documents. Le code source, par contre, comme je ne connais pas le language, j'ai jété un coup d'oeil mais je n'ai pu pas faire une évaluation plus approfondie, à cause de manque de compétence.

2022-08-15 14:36 UTC, torjc01 commented on _experimentations/ceai-cqen-documentation/2022-07-26-installation_asea_ceai.md
> +    <img src="./images/mcn.png">
```suggestion
    <img src="https://github.com/CQEN-QDCE/.github/blob/main/images/mcn.png" />
```

2022-08-15 14:38 UTC, torjc01 commented on _experimentations/ceai-cqen-documentation/2022-07-26-installation_asea_ceai.md
> +    <img src="./images/mcn.png">
Voici comme suggestions la seule ligne que je penses que tu pourrais changer.

2022-08-15 14:46 UTC, merged